export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-3xl mx-auto px-6 py-12">
        <div className="mb-8">
          <a href="/" className="text-blue-600 hover:underline text-sm">← Back to MyNitrends</a>
        </div>

        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-gray-500 mb-8">Last updated: {new Date().toLocaleDateString()}</p>

        <div className="prose prose-gray max-w-none space-y-6">
          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">1. Acceptance of Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              By accessing or using MyNitrends ("the Service"), you agree to be bound by these Terms of Service.
              If you do not agree to these terms, please do not use the Service. MyNitrends is an AI-powered
              social media automation tool that generates and publishes content to your Facebook Pages.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">2. Description of Service</h2>
            <p className="text-gray-600 leading-relaxed mb-2">MyNitrends provides the following services:</p>
            <ul className="list-disc list-inside text-gray-600 space-y-1">
              <li>AI-powered trend discovery and analysis.</li>
              <li>Automated social media post generation using artificial intelligence.</li>
              <li>AI-generated images for social media posts.</li>
              <li>Scheduled publishing to Facebook Pages.</li>
              <li>Engagement tracking and analytics.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">3. User Responsibilities</h2>
            <p className="text-gray-600 leading-relaxed mb-2">As a user of MyNitrends, you agree to:</p>
            <ul className="list-disc list-inside text-gray-600 space-y-1">
              <li>Provide accurate and complete information when creating your account.</li>
              <li>Review all AI-generated content before it is published to your Pages.</li>
              <li>Ensure that published content complies with Facebook's Community Standards and Terms of Service.</li>
              <li>Not use the Service to generate or publish content that is illegal, harmful, or violates the rights of others.</li>
              <li>Maintain the security of your account credentials and access tokens.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">4. AI-Generated Content</h2>
            <p className="text-gray-600 leading-relaxed">
              Content generated by MyNitrends is created using artificial intelligence and may not always be
              accurate, appropriate, or suitable for your audience. You are solely responsible for reviewing
              and approving all content before publication. We recommend reviewing all generated posts before
              they are published. You can configure the app to require manual approval or enable auto-posting
              at your own discretion.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">5. Facebook Integration</h2>
            <p className="text-gray-600 leading-relaxed">
              By connecting your Facebook account, you authorize MyNitrends to access and manage your
              Facebook Pages as described in our Privacy Policy. You can revoke this access at any time by
              removing MyNitrends from your Facebook account settings. We comply with Facebook's Platform
              Terms and Developer Policies.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">6. Intellectual Property</h2>
            <p className="text-gray-600 leading-relaxed">
              Content generated by the Service is provided to you for your use. You retain ownership of the
              content you publish through our Service. The MyNitrends application, its code, design, and
              branding remain the intellectual property of MyNitrends.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">7. Limitation of Liability</h2>
            <p className="text-gray-600 leading-relaxed">
              MyNitrends is provided "as is" without warranties of any kind. We are not liable for any
              damages arising from the use of our Service, including but not limited to: inaccurate
              AI-generated content, loss of data, or any consequences of content published through our
              Service. You use auto-posting features at your own risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">8. Service Availability</h2>
            <p className="text-gray-600 leading-relaxed">
              We strive to maintain the Service's availability but do not guarantee uninterrupted access.
              The Service depends on third-party APIs (Facebook, GROQ, Hugging Face) which may experience
              downtime or changes beyond our control. We may modify, suspend, or discontinue any part of
              the Service at any time.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">9. Account Termination</h2>
            <p className="text-gray-600 leading-relaxed">
              We reserve the right to suspend or terminate your account if you violate these Terms of
              Service. You may delete your account at any time by contacting us. Upon termination, your
              data will be handled as described in our Privacy Policy.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">10. Changes to Terms</h2>
            <p className="text-gray-600 leading-relaxed">
              We may update these Terms of Service from time to time. We will notify users of significant
              changes. Continued use of the Service after changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-gray-800 mb-3">11. Contact</h2>
            <p className="text-gray-600 leading-relaxed">
              For questions about these Terms of Service, please contact us at:{" "}
              <a href="mailto:support@mynitrends.com" className="text-blue-600 hover:underline">
                support@mynitrends.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
